Improve download feature #298
meditohq/medito-app pull request #334
Opened 2023-03-27 09:03 UTC by osamaasifoak

- Downloading feature improved
- Download screen logic changed to show the downloaded session

2023-03-27 17:02 UTC, michaelcspeed requested changes
Nice! Just a few small comments. Also please take a look at the check annotations on the Files changed tab. And there are some conflicts now - probably just small things

2023-03-27 17:02 UTC, michaelcspeed commented on lib/view_model/background_sounds/background_sounds_viewmodel.dart
> +      unawaited(SharedPreferencesService.addStringInSF(
I just had a moment where I was like "what is SF?" It's better to use clear and descriptive names for variables, functions, etc. This can make the code easier to read and understand for everyone who works with it.
I know I've done that a lot in this codebase before - would be good if we can clear that up as we go :D

2023-03-27 17:02 UTC, michaelcspeed commented on lib/views/downloads/downloads_view.dart
> +          // colorPrimary: parseColor(item.extras?[PRIMARY_COLOUR]),
still needed?

2023-03-27 17:02 UTC, michaelcspeed commented on lib/views/packs/pack_list_item.dart
> +      child: data.icon ?? NetworkImageComponent(url: data.cover!),
We should avoid using `!` because if it's null, it'll crash. Instead either check for a null value first, or allow the url to accept a nullable type :)

2023-03-27 17:02 UTC, michaelcspeed commented on lib/views/player/components/bottom_actions/components/audio_download_component.dart
> +    return downloadAudioProvider.downloadingProgress[downloadFileKey]! / 100;
also here, it it's null we should maybe return 0?

2023-03-27 17:02 UTC, michaelcspeed commented on lib/views/player/player_view.dart
> +  void setBackgroundSound(AudioPlayerNotifier _audioPlayerNotifier) {
Function parameters are already local to the function and cannot be accessed outside of it, so marking them as private with _ is redundant :)

2023-03-27 21:31 UTC, osamaasifoak commented on lib/view_model/background_sounds/background_sounds_viewmodel.dart
> +      unawaited(SharedPreferencesService.addStringInSF(
I always try my best to give them a meaningful name. Lol, Idk why I did that but yeah thanks for mentioning it. I will change it.

2023-03-27 21:32 UTC, osamaasifoak commented on lib/views/downloads/downloads_view.dart
> +          // colorPrimary: parseColor(item.extras?[PRIMARY_COLOUR]),
No, I will remove this

2023-03-27 21:33 UTC, osamaasifoak commented on lib/views/packs/pack_list_item.dart
> +      child: data.icon ?? NetworkImageComponent(url: data.cover!),
Hmm, you're right. Let me see what I can do here thanks

2023-03-27 21:35 UTC, osamaasifoak commented on lib/views/player/components/bottom_actions/components/audio_download_component.dart
> +    return downloadAudioProvider.downloadingProgress[downloadFileKey]! / 100;
I also handled the null case. But I can add a condition here for returning 0.

2023-03-27 21:37 UTC, osamaasifoak commented on lib/views/player/player_view.dart
> +  void setBackgroundSound(AudioPlayerNotifier _audioPlayerNotifier) {
I know it seems like I mistakenly did that

2023-03-27 21:58 UTC, osamaasifoak commented on lib/views/packs/pack_list_item.dart
> +      child: data.icon ?? NetworkImageComponent(url: data.cover!),
Can we use a placeholder image if the URL is null?

2023-03-28 20:08 UTC, michaelcspeed commented on lib/view_model/background_sounds/background_sounds_viewmodel.dart
> +      unawaited(SharedPreferencesService.addStringInSF(
no worries, we all miss stuff when writing this much code - that's why we do PR reviews :)

2023-03-28 20:08 UTC, michaelcspeed commented on lib/views/packs/pack_list_item.dart
> +      child: data.icon ?? NetworkImageComponent(url: data.cover!),
yeah good idea!

2023-03-28 20:11 UTC, michaelcspeed approved these changes

2023-04-01 11:09 UTC, merged